#! /usr/bin/env python3
# Using /home/teuben/LMT/lmtoy/data_lmt/unity/data_lmt.log
# 2018-S1-MU-79 - Science
#   script generated by source_obsnum.sh
import os
import sys

from lmtoy import runs

project="2018-S1-MU-79"

# Dictionary of sources, each with a list of obsnum's in this project
# negative obsnums are ignored in the combinations. See also comments.txt
# for obsnum specific comments and parameters!
on = {}

on["GP_J1448"] = \
 [ 88452, 88454, 88456, 88458, 88595, 88597, 88601, 88603, 88607, 88609, 88611, 88613, 88617, 88734, 88738, 88742, 88746, 88750, 88754, 88758, 88762, 88766, 88980, 88984, 90054, 90056, 90058, 90060, 90066, 90068, 90070,]

on["GP_J1735"] = \
 [ 84388, 84392, 84396, 84400, 84404, 84408, 84412, 84447, 84451, 84455, 84459, 84463, 84467, 84505, 84511, 84517, 84521, 84525, 84643, 84647, 84651, 90171, 90173, 90175, 90294, 90296, 90298, 90300, 90489, 90491, 90493, 90495, 90497, 90501, 90672, 90674, 90676, 90678, 90680, 90684, 90686, 90688, 90690, 90692,]

on["UM_488"] = \
 [ 84217, 84219, 84221, 84223, 88443, 88445, 88447, 88561, 88563, 88567, 88569, 88573, 88575, 88579, 88581, 88583, 88718, 88722, 88726, 90032, 90034, 90036, 90038, 90042, 90044, 90046, 90048,]

# parameters for the first pass of the pipeline (restart=1 is automatically enforced here)
pars1 = {}

pars1["GP_J1448"] = ""
pars1["GP_J1735"] = ""
pars1["UM_488"] = ""

# parameters for the (optional) second pass of the pipeline (e.g. for bank=0)
pars2 = {}

pars2["GP_J1448"] = ""
pars2["GP_J1735"] = ""
pars2["UM_488"] = ""

# parameters for the (optional) third pass of the pipeline (usually for bank=1)
pars3 = {}

pars3["GP_J1448"] = ""
pars3["GP_J1735"] = ""
pars3["UM_488"] = ""

# Found 3 source(s) for 2018-S1-MU-79

if __name__ == "__main__":
    runs.mk_runs(project, on, pars1, pars2, pars3, sys.argv)
